### ISSUE TITLE
Zookeeper integration

### ISSUE THREAD

**Issue by lxsameer** [Codamic/basilisk#2]
In order to keep track of our schedulers and workers state and performing operations like leader election we need to implement a full fledged **zookeeper** component and utility function.

**Comment by hamidr** [comment]
first i have not used it before.
i have to fire it on my pc first.

**Comment by lxsameer** [comment]
Just use the `repl.yml` in the source tree as your `docker-compose` configuration.

**Comment by hamidr** [comment]
ok will try to run it today.
